version: '3.7' # using a more recent version of Docker Compose

services:
  db:
    image: postgres:15.6
    restart: always
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Deng_pf1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/demo
      QUARKUS_DATASOURCE_USERNAME: admin
      QUARKUS_DATASOURCE_PASSWORD: Deng_pf1234
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app # Mounts the project directory to the Docker container
#    command: ./mvnw quarkus:dev -Dquarkus.profile=dev -Dquarkus.container-image.build=false -Dquarkus.container-image.push=false # Command to run Quarkus in dev mode

volumes:
  postgres_data:
