version: '3.7' # using a more recent version of Docker Compose

services:
  db:
    image: postgres:15.6
    restart: always
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Deng_pf1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
